import LoginPage from "./pages/Login.jsx";
import SignupPage from "./pages/signup.jsx";
import Home from "./pages/Home.jsx";
import CreateProduct from './pages/createProduct.jsx';
import MyProducts from "./pages/myProduct.jsx";
import Cart from "./pages/cart.jsx";
import ProductDetails from "./pages/productDetails.jsx";
import Profile from "./pages/profilePage.jsx";
import CreateAddress from "./pages/Address.jsx";
import SelectAddress from "./pages/SelectAddress.jsx";
import OrderConfirmation from "./pages/OrderConfimation.jsx";
import MyOrdersPage from "./pages/Orders.jsx";
import PrivateRoute from "./Router/PrivateRouter.jsx";
export {LoginPage,SignupPage,Home,CreateProduct,MyProducts, Cart , ProductDetails ,Profile, CreateAddress ,SelectAddress, OrderConfirmation , MyOrdersPage, PrivateRoute};