import LoginPage from "./pages/Login.jsx";
import SignupPage from "./pages/Signup.jsx";
import Home from "./pages/Home.jsx";
import CreateProduct from './pages/createProduct.jsx';
import MyProducts from "./pages/myProduct.jsx";
import Cart from "./pages/cart.jsx";
import Profile from "./pages/profilePage.jsx";
import ProductDetails from "./pages/productDetails.jsx";
import CreateAddress from "./pages/Adress.jsx";
export {LoginPage,SignupPage,Home,CreateProduct,MyProducts, Cart , ProductDetails,Profile, CreateAddress};